---
apiVersion: v2
name: netbox
description: |
  An IP address management (IPAM) and data center infrastructure management (DCIM) tool.

  Important; With chart version 4.0.0 there are major upgrades to the packaged Redis and Postgres,
  as well as a major version bump of Netbox that introduces housekeeping. Take care when upgrading.
icon: https://raw.githubusercontent.com/digitalocean/netbox/develop/netbox/project-static/img/netbox.ico
appVersion: 3.6.3

type: application
version: 5.5.3
maintainers:
  - name: Tommy Skaug
    email: tommy@skaug.me
