#+TITLE: Minimal and Opinionated Helm Charts
#+DATE:  2023-10-18


Backend-focused and UX optimized minmal charts built for use with deployments based on Flux. 

*** Chart Implementation Guidelines

**** TODO Example chart definition

#+BEGIN_SRC
$ helm repo add tommy-skaug-charts ghcr.io/tommy-skaug/charts
#+END_SRC

Check out the ingress configuration in [[./docs/ingress.org][ingress.org]]

*** Charts

**** [[charts/conduit][Conduit]]

An efficient and self-contained Matrix server using an embedded RocksDB database.

**** [[][Attic]]

[[https://github.com/zhaofengli/attic][Attic]] (introduction post [[https://discourse.nixos.org/t/introducing-attic-a-self-hostable-nix-binary-cache-server/24343][here]]) is a Nix Binary Cache server that reduces the time to compile and distribute builds.


*** Usage



** License

Repo was inspired by [[https://gitlab.com/ananace/charts][ananace]] (some parts imported and rewritten).

The general license of this repo is DWTFYWTPB, but it is Apache v2 in some of the repos which were built on other's work. See the individual chart for details.




helm install dispatch ./dispatch -f values-local.yaml

kubectl describe pod 

helm delete dispatch
