version: "3"

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"

tasks:
  validate:
    desc: Validate charts
  silent: "False"
  cmds:
  - |
    for f in $(ls -d charts/* | fgrep -v '.yaml')
      helm lint $f
    end

  install:
    desc: Manual install of chart
    cmds:
    - helm install tmp {{ .CLI_ARGS }}

  reinstall:
    desc: Remove installed chart
    cmds:
    - helm uninstall tmp
    - helm install tmp {{ .CLI_ARGS }}

  remove:
    desc: Remove installed chart
    cmds:
    - helm uninstall tmp

  default:
    silent: true
    cmds:
    - task -l
