{{- if and .Values.persistence.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "conduit.fullname" . }}
  labels:
    {{- include "conduit.labels" . | nindent 4 }}
  {{- with .Values.persistence.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- with .Values.persistence.storageClass }}
  {{-  if (eq "-" .) }}
  storageClassName: ""
  {{-  else }}
  storageClassName: {{ . | quote }}
  {{-  end }}
  {{- end }}
{{- end -}}