apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dispatch.fullname" . }}-config
data:
  POSTGRES_HOSTNAME: {{ .Values.postgres.hostname | quote }}
  POSTGRES_DATABASE_NAME: {{ .Values.postgres.database_name | quote }}
  POSTGRES_PORT: {{ .Values.postgres.port | quote }}