apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dispatch.fullname" . }}-config
  labels:
    {{- include "dispatch.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap.general | nindent 2 }}