{{- if .Values.core.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dispatch.fullname" . }}-core
  labels:
    {{- include "dispatch.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "dispatch.fullname" . }}-core
  template:
    metadata:
      labels:
        app: {{ include "dispatch.fullname" . }}-core
    spec:
      initContainers:
        - name: db-init
          image: "{{ .Values.initContainers.dbInit.image.repository }}:{{ .Values.initContainers.dbInit.image.tag }}"
          envFrom:
            - secretRef:
                name: {{ .Values.postgres.secretName }}
      containers:
        - name: core
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MJML_PATH
              value: /node_modules/.bin
            - name:  DISPATCH_UI_URL
              value: "{{ .Values.url }}"
            - name:  DATABASE_HOSTNAME
              value: "{{ .Values.postgres.hostname }}"
            - name:  DATABASE_PORT
              value: "{{ .Values.postgres.port }}"
            - name:  DATABASE_NAME
              value: "{{ .Values.postgres.database_name }}"
            {{ if eq .Values.authentication.provider_slug "dispatch-auth-provider-header" }}
            - name:  DISPATCH_AUTHENTICATION_PROVIDER_SLUG
              value: "{{ .Values.authentication.provider_slug }}"
            - name:  DISPATCH_AUTHENTICATION_PROVIDER_HEADER_NAME
              value: "{{ .Values.authentication.header.header_name }}"
            {{ end }} 
          envFrom:
            - secretRef:
                name: {{ .Values.envFromSecret }}
{{- end }}