{{- if .Values.scheduler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dispatch.fullname" . }}-scheduler
  labels:
    {{- include "dispatch.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "dispatch.fullname" . }}-scheduler
  template:
    metadata:
      labels:
        app: {{ include "dispatch.fullname" . }}-scheduler
    spec:
      containers:
        - name: scheduler
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{ .Values.scheduler.container.command }}
          env: {{ .Values.scheduler.container.env }}
          envFrom:
            - secretRef:
                name: {{ .Values.scheduler.container.envFrom.secretRef.name }}
{{- end }}