apiVersion: v1
kind: Service
metadata:
  name: {{ include "dispatch.fullname" . }}-web
  labels:
    {{- include "dispatch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: 8000
      protocol: TCP
  selector:
    app: {{ include "dispatch.fullname" . }}-web
