{{- if .Values.scheduler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dispatch.fullname" . }}-web
  labels:
    {{- include "dispatch.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "dispatch.fullname" . }}-web
  template:
    metadata:
      labels:
        app: {{ include "dispatch.fullname" . }}-web
    spec:
      initContainers:
        - name: web-db-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["dispatch", "web", "database", "init"]
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{ .Values.web.container.command }}
          ports:
            - containerPort: {{ .Values.web.container.port }}
          envFrom:
            - secretRef:
                name: {{ .Values.web.container.envFrom.secretRef.name }}
{{- end }}