apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "penpot.fullname" . }}-db-init
  labels:
    {{- include "penpot.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: penpot-db-init
          image: "{{ .Values.postgres.dbInit.image.repository }}:{{ .Values.postgres.dbInit.image.tag }}"
          envFrom:
            - secretRef:
                name: {{ .Values.postgres.secretName }}
  backoffLimit: 3