apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "penpot.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "penpot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "penpot.backendSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "penpot.backendSelectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "penpot.serviceAccountName" . }}
      securityContext:
        podSecurityContext:
          enabled: true
          fsGroup: 1001

      containers:
        - name: {{ .Chart.Name }}-backend
          image:
            repository: "penpotapp/backend:{{ .Values.penpotVersion.tag }}"
            imagePullPolicy: IfNotPresent
          containerSecurityContext:
            enabled: true
            runAsUser: 1001
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - all
            readOnlyRootFilesystem: false
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /opt/data
              name: app-data
              readOnly: false
          env:
            - name: PENPOT_PUBLIC_URI
              value: {{ .Values.config.publicURI | quote }}
            - name: PENPOT_FLAGS
              value: "$PENPOT_FLAGS {{ .Values.config.flags }}"
            - name: PENPOT_TELEMETRY_ENABLED
              value: false
            - name: PENPOT_REGISTRATION_DOMAIN_WHITELIST
              value: {{ .Values.registrationDomainWhitelist | quote }}
          envFrom:
            - secretRef:
                name: {{ .Values.envFromSecret }}
          ports:
            - name: http
              containerPort: 6060
              protocol: TCP
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      volumes:
      - name: app-data
        emptyDir: {}
