envFromSecret: penpot-secret
penpotVersion: 1.19.3

publicURL: "http://localhost:8080"
registrationDomainWhitelist: "localhost"
flags: "enable-registration enable-login enable-login-with-oidc disable-demo-users disable-demo-warning disable-secure-session-cookies"

serviceAccount:
  name: "penpot-sa"

backend:
  replicaCount: 1
  resources:
    limits: {}
    requests: {}

frontend:
  replicaCount: 1
  resources:
    limits: {}
    requests: {}

exporter:
  replicaCount: 1
  resources:
    limits: {}
    requests: {}

image:
  imagePullPolicy: IfNotPresent
  repositoryBackend: penpotapp/backend
  repositoryFrontend: penpotapp/frontend
  repositoryExporter: penpotapp/exporter

postgres:
  dbInit:
    repository: ghcr.io/onedr0p/postgres-init
    tag: "16"
  hostname: "postgres-rw.databases.svc.cluster.local"
  database_name: "penpot"
  port: "5432"
  secretName: penpot-secret
