image:
  repository: ghcr.io/tommy-skaug/dispatch
  tag: v20230919
  pullPolicy: Always

initContainers:
  dbInit:
    image:
      repository: ghcr.io/onedr0p/postgres-init
      tag: "16"
    envFrom:
      - secretRef:
          name: dispatch-secret

core:
  container:
    command: []

web:
  container:
    port: 8000
    command: ["dispatch", "server", "start", "dispatch.main:app", "--host=0.0.0.0"]
  service:
    type: ClusterIP
    port: 80

scheduler:
  command: ["dispatch", "scheduler", "start"]

postgres:
  hostname: "postgres-rw.databases.svc.cluster.local"
  database_name: "postgres"
  port: "5432"
  secretRef:
    name: dispatch-secret