envFromSecret: &secret dispatch-secret

image:
  repository: ghcr.io/tommy-skaug/dispatch
  tag: v20230919
  pullPolicy: Always

initContainers:
  dbInit:
    image:
      repository: ghcr.io/onedr0p/postgres-init
      tag: "16"
    envFrom:
      - secretRef:
          name: *secret

url: http://localhost:80

core:
  enabled: true

web:
  enabled: true
  service:
    type: ClusterIP
    port: 80

scheduler:
  enabled: true

postgres:
  hostname:      "postgres-rw.databases.svc.cluster.local"
  database_name: "dispatch"
  port:          "5432"
  secretRef:
    name: *secret