envFromSecret: dispatch-secret

image:
  repository: ghcr.io/tommy-skaug/dispatch
  tag:        v20230919
  pullPolicy: Always

initContainers:
  dbInit:
    image:
      repository: ghcr.io/onedr0p/postgres-init
      tag: "16"
    envFrom:
      - secretRef:
          name: dispatch-secret

url: http://localhost:80

authentication:
  #provider_slug: dispatch-auth-provider-basic
  # provider_slug: dispatch-auth-provider-pkce
  pkce:
    dont_verify_at_hash: false
    openid_connect_url: 
    client_id: 
    use_id_token: 
  provider_slug: dispatch-auth-provider-header
  header:
    header_name: Tailscale-User-Login


core:
  enabled: true

web:
  enabled: true
  service:
    type: ClusterIP
    port: 80

scheduler:
  enabled: true

postgres:
  hostname:      "postgres-rw.databases.svc.cluster.local"
  database_name: "dispatch"
  port:          "5432"
  secretName:    dispatch-secret