image:
  repository: ghcr.io/tommy-skaug/dispatch
  tag: v20230919
  pullPolicy: Always

initContainers:
  dbInit:
    image:
      repository: ghcr.io/onedr0p/postgres-init
      tag: "16"
    envFrom:
      - secretRef:
          name: dispatch-secret

core:
  container:
    command: []

web:
  container:
    port: 8000
    command: ["server", "start", "dispatch.main:app", "--host=0.0.0.0"]
  service:
    type: ClusterIP
    port: 80

scheduler:
  command: ["scheduler", "start"]

configMap:
  general:
    COMPOSE_PROJECT_NAME: "dispatch"
    DATABASE_HOSTNAME: "postgres-rw.databases.svc.cluster.local"
    DATABASE_NAME: "dispatch"
    DATABASE_PORT: "5432"

postgres:
  secretRef:
    name: dispatch-secret