replicaCount: 1
image:
  repository: ghcr.io/ollama-webui/ollama-webui
  tag: "main"
apiUrl: "http://ollama.llm.svc.cluster.local:11434/api"
servicePort: 8080
resources:
  limits:
    cpu: "500m"
    memory: "500Mi"
volumeSize: 1Gi
nodeSelector: {}
tolerations: []
service:
  type: NodePort
persistence:
  existingClaim: ollama-web
