---
apiVersion: v2
name: sliding-sync-proxy
description: An implementation of MSC3575
appVersion: "0.99.11"

type: application
version: 0.2.5
maintainers:
  - name: Tommy Skaug
    email: tommy@skaug.me