apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dispatch-ingress
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: dispatch-web
      port:
        number: 80
  tls:
  - hosts:
    - dispatch
