---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-extra
  labels:
    app.kubernetes.io/name: {{ include "netbox.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "netbox.chart" . }}
data:
  extra.py: |
    {{- .Values.extraConfiguration | nindent 4 }}
{{- if .Values.extraPlugins }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-plugins
  labels:
    app.kubernetes.io/name: {{ include "netbox.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "netbox.chart" . }}
data:
  plugins.py: |
    {{- .Values.extraPlugins | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "netbox.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "netbox.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "netbox.chart" . }}
data:
  tmp: "test"
{{- range $key, $value := .Values.extraEnv }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
