---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-extra
  labels:
    {{- include "netbox.labels" . | nindent 4 }}
data:
  extra.py: |
    {{- .Values.extraConfiguration | nindent 4 }}
{{- if .Values.extraPlugins }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-plugins
  labels:
    {{- include "netbox.labels" . | nindent 4 }}
data:
  plugins.py: |
    {{- .Values.extraPlugins | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "netbox.fullname" . }}
  labels:
    {{- include "netbox.labels" . | nindent 4 }}
data:
  tmp: "test"
{{- range $key, $value := .Values.extraEnv }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
