apiVersion: v1
kind: Service
metadata:
  name: {{ include "ollama.fullname" . }}-service
spec:
  type: ClusterIP 
  selector:
    app: {{ include "ollama.fullname" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.servicePort }}
      # If using NodePort, you can optionally specify the nodePort:
      # nodePort: 30000