apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "excalidraw.name" . }}
  labels:
    {{- include "excalidraw.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "excalidraw.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "excalidraw.name" . }}
    spec:
      serviceAccountName: "excalidraw-sa"
      securityContext: {}
      containers:
        - name: {{ .Chart.Name }}
          securityContext: {}
            # capabilities:
            #   drop:
            #   - ALL
            # readOnlyRootFilesystem: true
            # runAsNonRoot: true
            # runAsUser: 1000

          image: "ghcr.io/tommy-skaug/excalidraw:v0.17.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}