apiVersion: v1
kind: Service
metadata:
  name: {{ include "excalidraw.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
