---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hasura
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: hasura-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Hasura
        HASURA_GRAPHQL_ADMIN_SECRET: "{{ .HASURA_GRAPHQL_ADMIN_SECRET }}"
        HASURA_GRAPHQL_DATABASE_URL: |-
          postgres://hasura:{{ .HASURA_POSTGRES_PASS }}@postgres-rw.databases.svc.cluster.local/hasura
        # Postgres Init
        INIT_POSTGRES_DBNAME:     hasura
        INIT_POSTGRES_HOST:       postgres-rw.databases.svc.cluster.local
        INIT_POSTGRES_USER:       hasura
        INIT_POSTGRES_PASS:       "{{ .HASURA_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # Vars
        PUBLIC_DOMAIN: ${PUBLIC_DOMAIN}
  dataFrom:
    - extract:
        key: hasura
    - extract:
        key: postgres
