apiVersion: v2
name: hasura-engine
description: GraphQL Engine to make data accessible over a GraphQL API
type: application
version: 0.1.3
maintainers:
- name: Tommy Skaug
  email: tommy@skaug.me
icon: https://avatars.githubusercontent.com/u/13966722?s=200&v=4
keywords:
- kubernetes
- graphql
- server
- postgres
- web
- api
- rest
sources:
- https://github.com/hasura/graphql-engine
- https://hasura.io/docs/latest/index/
