image:
  repository: hasura/graphql-engine
  tag: v2.36.2
  pullPolicy: IfNotPresent

initContainers:
  dbInit:
    image:
      repository: ghcr.io/onedr0p/postgres-init
      tag: "16"
    envFrom:
    - secretRef:
        name: dispatch-secret

replicas: "1"

service:
  type: ClusterIP
  port: 80

features:
  devMode: true
  console: true

corsDomains: "*"

envFromSecret: hasura-secret
admin:
  secretKey: HASURA_GRAPHQL_ADMIN_SECRET
jwt:
  jwksUrl: HASURA_GRAPHQL_JWT_SECRET
postgres:
  secretKey: HASURA_GRAPHQL_DATABASE_URL
